<script setup lang="ts">
/**
 * AdaMorningHandoff: the conversational coworker note from Ada to Marc.
 *
 * This is the EMOTIONAL cheat-code moment on the Today page. A cold
 * visitor reads this BEFORE any operator-mode UI starts and the read is
 * "oh, that's what a coworker note feels like," not "here are my metrics."
 *
 * Visual treatment is deliberately NOT a metric card:
 *   - Soft brand-tinted background, no chip rows, no buttons
 *   - Slightly larger line-height than usual cards (reads as prose)
 *   - Avatar bubble + "Ada · this morning" timestamp signals "person wrote
 *     this to you"
 *   - Sign-off "Ada" on its own line, in the same casual register
 *
 * Content is HARDCODED for the demo. In a real customer dashboard this
 * would be generated by an LLM each morning summarizing what happened
 * overnight + flagging what needs the operator's eyes today.
 *
 * Ordering rationale: placed BEFORE the cheat-code hero ("What Ada
 * replaces") because:
 *   1. The handoff is emotional ("this feels like a coworker")
 *   2. The cheat-code hero is rational ("here's the payroll math")
 *   For a cold visitor, the emotional read needs to land first.
 *   For Marc (returning operator), the handoff is the daily value;
 *   the cheat-code math is irrelevant after week 1.
 */

defineProps<{
  ownerFirstName: string
  /** Optional override for the "this morning" timestamp text. */
  timestamp?: string
}>()
</script>

<template>
  <section class="rounded-card border border-brand/25 bg-brand/[0.04] px-5 py-5 sm:px-6 sm:py-6">
    <!-- Header: Ada avatar + name + timestamp -->
    <header class="flex items-center gap-3 mb-4">
      <div class="h-9 w-9 rounded-full bg-brand text-ink-inverse flex items-center justify-center text-sm font-bold flex-shrink-0">
        A
      </div>
      <div class="flex-1 min-w-0">
        <div class="flex items-baseline gap-2 flex-wrap">
          <span class="text-sm font-bold text-ink">Ada</span>
          <span class="text-[11px] text-ink-muted">{{ timestamp ?? 'this morning · 6:30am' }}</span>
        </div>
        <p class="text-[11px] text-ink-muted leading-snug">handoff note before you get on the road</p>
      </div>
    </header>

    <!-- The note itself: reads as real prose, not a card -->
    <div class="space-y-3.5 text-[13.5px] text-ink leading-relaxed max-w-2xl">
      <p>Hey {{ ownerFirstName }}, quick handoff before you get on the road today.</p>

      <p>
        Caught a <strong>7:43pm call from Tampa</strong> last night about a master bath remodel. She wanted Thursday, I booked her 10am. Estimated $45K job. She mentioned her neighbor used you in 2024, so I flagged it as a referral lead source.
      </p>

      <p>
        <strong>Heather Cole</strong> replied to the kitchen reactivation: "yeah, we've been thinking about it." Big one. She's the bath customer from 18 months ago. I drafted a no-commitment walkthrough invite but you might want to send this yourself, the warmth deserves a personal touch.
      </p>

      <p>
        <strong>Pat Owens</strong> left a 4-star review (cabinet delivery slipped). Drafted an honest reply that acknowledges the slip and names the vendor switch you made because of it. Your call before I post.
      </p>

      <div class="pt-1">
        <p class="text-[12px] text-ink-muted mb-1.5"><strong class="text-ink">A few things I noticed:</strong></p>
        <ul class="space-y-1.5 text-[13px] text-ink-muted">
          <li>
            <span class="text-brand">·</span>
            LSA inquiries spiked 40% Tuesday afternoon. Probably worth tuning up bid strategy before the window closes.
          </li>
          <li>
            <span class="text-brand">·</span>
            You're 12 reviews from crossing 140 (Google ranking lift). 18 recent customers haven't been asked yet, I can draft all 18 if you want.
          </li>
          <li>
            <span class="text-brand">·</span>
            Three reviews this month called out Diego by name. Worth featuring him in next month's newsletter.
          </li>
        </ul>
      </div>

      <p class="pt-1">That's it. Have a good one out there.</p>

      <p class="text-ink"><span class="text-ink-muted">Ada</span></p>
    </div>
  </section>
</template>
