// Focal Point Church - who to ask to serve.
//
// Ranked by the two signals that predict a yes, from Planning Center:
//   tier 1  in a Growth Group AND dropping kids off
//   tier 2  in a Growth Group
//   tier 3  dropping kids off
// Within a tier, more Sundays present ranks higher. "sundays" counts distinct
// Sundays they physically dropped a child off in the window, which is a
// recorded appearance; group membership alone is not, so tier 2 has no
// attendance signal and is ordered by group involvement instead.
//
// Everyone here is EXCLUDED from serving already, and the same over-serving
// rule the burnout signal uses is applied, so a name suggested here can never
// be a name the church is being told to protect.
//
// Names are real congregants, so this follows the skip-worktree pattern: the
// committed copy is anonymised, the on-disk copy is real.
// Generated 2026-08-27 from a 120-day window. Regenerate with
// scripts/pull-serve-candidates.mjs then scripts/gen-serve-candidates.mjs.
export interface ServeCandidate {
  name: string
  /** 1 = group + kids drop-off, 2 = group only, 3 = kids drop-off only */
  tier: 1 | 2 | 3
  /** Distinct Sundays they dropped a child off in the window. */
  sundays: number
  groups: string[]
}

export const serveCandidates: {
  generated: string
  windowDays: number
  /** Exact totals, even where the list below is capped. */
  totals: { tier1: number; tier2: number; tier3: number; all: number }
  people: ServeCandidate[]
} = {
  generated: '2026-08-27',
  windowDays: 120,
  totals: { tier1: 46, tier2: 540, tier3: 201, all: 787 },
  people: [
    { name: "Candidate 1", tier: 1, sundays: 14, groups: ["Group 1","Group 2","Group 3","Group 4"] },
    { name: "Candidate 2", tier: 1, sundays: 14, groups: ["Group 1","Group 2"] },
    { name: "Candidate 3", tier: 1, sundays: 12, groups: ["Group 1"] },
    { name: "Candidate 4", tier: 1, sundays: 11, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 5", tier: 1, sundays: 10, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 6", tier: 1, sundays: 10, groups: ["Group 1"] },
    { name: "Candidate 7", tier: 1, sundays: 10, groups: ["Group 1"] },
    { name: "Candidate 8", tier: 1, sundays: 9, groups: ["Group 1","Group 2"] },
    { name: "Candidate 9", tier: 1, sundays: 9, groups: ["Group 1"] },
    { name: "Candidate 10", tier: 1, sundays: 9, groups: ["Group 1"] },
    { name: "Candidate 11", tier: 1, sundays: 8, groups: ["Group 1"] },
    { name: "Candidate 12", tier: 1, sundays: 7, groups: ["Group 1"] },
    { name: "Candidate 13", tier: 1, sundays: 7, groups: ["Group 1"] },
    { name: "Candidate 14", tier: 1, sundays: 7, groups: ["Group 1"] },
    { name: "Candidate 15", tier: 1, sundays: 6, groups: ["Group 1"] },
    { name: "Candidate 16", tier: 1, sundays: 6, groups: ["Group 1"] },
    { name: "Candidate 17", tier: 1, sundays: 6, groups: ["Group 1"] },
    { name: "Candidate 18", tier: 1, sundays: 5, groups: ["Group 1"] },
    { name: "Candidate 19", tier: 1, sundays: 5, groups: ["Group 1"] },
    { name: "Candidate 20", tier: 1, sundays: 5, groups: ["Group 1"] },
    { name: "Candidate 21", tier: 1, sundays: 4, groups: ["Group 1"] },
    { name: "Candidate 22", tier: 1, sundays: 4, groups: ["Group 1"] },
    { name: "Candidate 23", tier: 1, sundays: 4, groups: ["Group 1"] },
    { name: "Candidate 24", tier: 1, sundays: 3, groups: ["Group 1","Group 2","Group 3","Group 4","Group 5","Group 6","Group 7","Group 8","Group 9","Group 10","Group 11","Group 12","Group 13"] },
    { name: "Candidate 25", tier: 1, sundays: 3, groups: ["Group 1"] },
    { name: "Candidate 26", tier: 1, sundays: 3, groups: ["Group 1"] },
    { name: "Candidate 27", tier: 1, sundays: 3, groups: ["Group 1"] },
    { name: "Candidate 28", tier: 1, sundays: 3, groups: ["Group 1"] },
    { name: "Candidate 29", tier: 1, sundays: 2, groups: ["Group 1","Group 2"] },
    { name: "Candidate 30", tier: 1, sundays: 2, groups: ["Group 1"] },
    { name: "Candidate 31", tier: 1, sundays: 2, groups: ["Group 1"] },
    { name: "Candidate 32", tier: 1, sundays: 2, groups: ["Group 1"] },
    { name: "Candidate 33", tier: 1, sundays: 2, groups: ["Group 1"] },
    { name: "Candidate 34", tier: 1, sundays: 1, groups: ["Group 1","Group 2"] },
    { name: "Candidate 35", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 36", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 37", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 38", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 39", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 40", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 41", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 42", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 43", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 44", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 45", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 46", tier: 1, sundays: 1, groups: ["Group 1"] },
    { name: "Candidate 47", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3","Group 4"] },
    { name: "Candidate 48", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3","Group 4"] },
    { name: "Candidate 49", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3","Group 4"] },
    { name: "Candidate 50", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3","Group 4"] },
    { name: "Candidate 51", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 52", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 53", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 54", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 55", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 56", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 57", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 58", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 59", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 60", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 61", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 62", tier: 2, sundays: 0, groups: ["Group 1","Group 2","Group 3"] },
    { name: "Candidate 63", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 64", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 65", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 66", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 67", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 68", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 69", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 70", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 71", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 72", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 73", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 74", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 75", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 76", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 77", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 78", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 79", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 80", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 81", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 82", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 83", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 84", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 85", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 86", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 87", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 88", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 89", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 90", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 91", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 92", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 93", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 94", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 95", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 96", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 97", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 98", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 99", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 100", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 101", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 102", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 103", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 104", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 105", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 106", tier: 2, sundays: 0, groups: ["Group 1","Group 2"] },
    { name: "Candidate 107", tier: 3, sundays: 16, groups: [] },
    { name: "Candidate 108", tier: 3, sundays: 16, groups: [] },
    { name: "Candidate 109", tier: 3, sundays: 15, groups: [] },
    { name: "Candidate 110", tier: 3, sundays: 15, groups: [] },
    { name: "Candidate 111", tier: 3, sundays: 14, groups: [] },
    { name: "Candidate 112", tier: 3, sundays: 14, groups: [] },
    { name: "Candidate 113", tier: 3, sundays: 13, groups: [] },
    { name: "Candidate 114", tier: 3, sundays: 13, groups: [] },
    { name: "Candidate 115", tier: 3, sundays: 13, groups: [] },
    { name: "Candidate 116", tier: 3, sundays: 12, groups: [] },
    { name: "Candidate 117", tier: 3, sundays: 11, groups: [] },
    { name: "Candidate 118", tier: 3, sundays: 11, groups: [] },
    { name: "Candidate 119", tier: 3, sundays: 11, groups: [] },
    { name: "Candidate 120", tier: 3, sundays: 11, groups: [] },
    { name: "Candidate 121", tier: 3, sundays: 11, groups: [] },
    { name: "Candidate 122", tier: 3, sundays: 11, groups: [] },
    { name: "Candidate 123", tier: 3, sundays: 10, groups: [] },
    { name: "Candidate 124", tier: 3, sundays: 10, groups: [] },
    { name: "Candidate 125", tier: 3, sundays: 10, groups: [] },
    { name: "Candidate 126", tier: 3, sundays: 10, groups: [] },
    { name: "Candidate 127", tier: 3, sundays: 10, groups: [] },
    { name: "Candidate 128", tier: 3, sundays: 9, groups: [] },
    { name: "Candidate 129", tier: 3, sundays: 9, groups: [] },
    { name: "Candidate 130", tier: 3, sundays: 9, groups: [] },
    { name: "Candidate 131", tier: 3, sundays: 9, groups: [] },
    { name: "Candidate 132", tier: 3, sundays: 9, groups: [] },
    { name: "Candidate 133", tier: 3, sundays: 9, groups: [] },
    { name: "Candidate 134", tier: 3, sundays: 8, groups: [] },
    { name: "Candidate 135", tier: 3, sundays: 8, groups: [] },
    { name: "Candidate 136", tier: 3, sundays: 8, groups: [] },
    { name: "Candidate 137", tier: 3, sundays: 7, groups: [] },
    { name: "Candidate 138", tier: 3, sundays: 7, groups: [] },
    { name: "Candidate 139", tier: 3, sundays: 7, groups: [] },
    { name: "Candidate 140", tier: 3, sundays: 7, groups: [] },
    { name: "Candidate 141", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 142", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 143", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 144", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 145", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 146", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 147", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 148", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 149", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 150", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 151", tier: 3, sundays: 6, groups: [] },
    { name: "Candidate 152", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 153", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 154", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 155", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 156", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 157", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 158", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 159", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 160", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 161", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 162", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 163", tier: 3, sundays: 5, groups: [] },
    { name: "Candidate 164", tier: 3, sundays: 4, groups: [] },
    { name: "Candidate 165", tier: 3, sundays: 4, groups: [] },
    { name: "Candidate 166", tier: 3, sundays: 4, groups: [] },
  ],
}
