// Focal Point Church - Burnout Watch (real serving load, from Planning Center
// SERVICES scheduling via scripts/gen-burnout.mjs). Flagged = scheduled 3+ times a
// month OR across 2+ teams; high = 4+/month OR 3+ teams. Check-ins are not used
// (they undercount serving). Staff excluded.
// LOCAL OVERRIDE (skip-worktree): real names live on disk only, never in git.
export interface BurnoutPerson { name: string; areas: string[]; campus: "english" | "brazilian" | "both"; perMonth: number; tier: "high" | "medium" }
export interface BurnoutDraft { id: string; name: string; context: string; draft: string }
export const focalPointBurnout: { flaggedPeople: number; highRisk: number; activeVolunteers: number; signal: string; people: BurnoutPerson[]; drafts: BurnoutDraft[] } = {
  flaggedPeople: 117, highRisk: 43, activeVolunteers: 376,
  signal: "Volunteers scheduled 3+ times a month, often across several teams, and still going. The people most likely to burn out and drop next. Today's over-servers are next quarter's drift.",
  people: [
  {"name":"Glenn Eppinger","areas":["Kids Point","Safety Team"],"campus":"english","perMonth":8,"tier":"high"},
  {"name":"Dave McNichols","areas":["Safety Team"],"campus":"english","perMonth":8,"tier":"high"},
  {"name":"Kristof Salopek","areas":["Hospitality"],"campus":"english","perMonth":7,"tier":"high"},
  {"name":"Mirabela Dragoiu","areas":["Prayer Leaders","Kids Point JR","First Impressions Team","K-3rd Grade"],"campus":"english","perMonth":6,"tier":"high"},
  {"name":"Andre Faleiros","areas":["Vocals 4th Service","Band 4th Service","Band"],"campus":"both","perMonth":6,"tier":"high"},
  {"name":"Daniel Rivera","areas":["Ushers","Parking Team","Hospitality"],"campus":"english","perMonth":6,"tier":"high"},
  {"name":"Javenson Romain","areas":["Band","Media Team","Youth Group Worship Team"],"campus":"english","perMonth":5,"tier":"high"},
  {"name":"Leslie Jameel","areas":["Prayer Leaders","First Impressions Team"],"campus":"english","perMonth":5,"tier":"high"},
  {"name":"Dawnita Anderson","areas":["Prayer Leaders","First Impressions Team"],"campus":"english","perMonth":5,"tier":"high"},
  {"name":"William Walters","areas":["Hospitality"],"campus":"english","perMonth":5,"tier":"high"},
  {"name":"Cristian Veguilla","areas":["Kids Point","Media Team","Hospitality","Tech"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"João Messias Teodoro","areas":["Vocals 4th Service","Band 4th Service","Kids 4th Service"],"campus":"brazilian","perMonth":4,"tier":"high"},
  {"name":"David Thomas","areas":["First Impressions Team","Host"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"Julissa Romain","areas":["Media Team","Kids Point"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"DJ Veguilla","areas":["Hospitality","Media Team"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"Linda Skipper","areas":["Hospitality"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"Lyndon Sims","areas":["Safety Team"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"Peter Davisson","areas":["Media Team"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"John Fritz","areas":["Parking Team"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"Aaron Score","areas":["Safety Team"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"Amanda Walters","areas":["Hospitality"],"campus":"english","perMonth":4,"tier":"high"},
  {"name":"Leandro Videira","areas":["Band 4th Service"],"campus":"brazilian","perMonth":4,"tier":"high"},
  {"name":"Kyria Thernelus","areas":["Band","Youth Group Worship Team","Overflow Tent","Media Team"],"campus":"english","perMonth":3,"tier":"high"},
  {"name":"Thayana Xavier Silva","areas":["Kids Point","Nursery - Saturday","K-3rd Grade","Host"],"campus":"english","perMonth":3,"tier":"high"},
  {"name":"Maria Rojas","areas":["Check-In Volunteers","Media Team","Check-In Team","Kids Point"],"campus":"english","perMonth":3,"tier":"high"},
  {"name":"Anthony Jr. Velasquez","areas":["Kids Point","Parking Team","Tech"],"campus":"english","perMonth":3,"tier":"high"},
  {"name":"Cassie Wiggins","areas":["Vocals","First Steps Nursery","Youth Group Worship Team"],"campus":"english","perMonth":3,"tier":"high"},
  {"name":"Anderson Nunes Grandi","areas":["Vocals 4th Service","Band 4th Service","Apoio Pastoral"],"campus":"brazilian","perMonth":3,"tier":"high"},
  {"name":"Jeshua Rodriguez","areas":["Band","Overflow Tent","Youth Group Worship Team"],"campus":"english","perMonth":3,"tier":"high"},
  {"name":"Jerome Mallory","areas":["Security 4th Service","Safety Team"],"campus":"both","perMonth":3,"tier":"medium"},
  {"name":"Regiane Teodoro","areas":["Vocals 4th Service","Kids 4th Service"],"campus":"brazilian","perMonth":3,"tier":"medium"},
  {"name":"Dana Bennett","areas":["First Steps Nursery","Host"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Jennifer Kneefe","areas":["First Impressions Team","Kids Point"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Shaun O'Dell","areas":["Vocals","First Impressions Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Caucheline Romain","areas":["Ushers","First Steps Nursery"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Ashley Elicier","areas":["First Steps Nursery","Hospitality"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"JR Rivera","areas":["Safety Team","First Impressions Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Sara Giaretta","areas":["Vocals 4th Service","Kids 4th Service"],"campus":"brazilian","perMonth":3,"tier":"medium"},
  {"name":"Lydia Salopek","areas":["Kids Point","Youth Group Worship Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Fernando Barros","areas":["Band 4th Service","Kids 4th Service"],"campus":"brazilian","perMonth":3,"tier":"medium"},
  {"name":"Cleusa Trindade","areas":["Kids 4th Service","Vocals 4th Service"],"campus":"brazilian","perMonth":3,"tier":"medium"},
  {"name":"Jonathan Jameel","areas":["Media Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Jim Thomas","areas":["Safety Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Bogdan Gradinariu","areas":["Safety Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Peter Bankole","areas":["Ushers"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Joan De Pass","areas":["Kids Point JR"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Mark Manigold","areas":["Parking Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Alexander A. Rodriguez","areas":["Safety Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Christy Lacey","areas":["Host"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Nathalie Lubin","areas":["Ushers"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Isabel Lamberty","areas":["Ushers"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Tracy Lipoa Thomas","areas":["First Impressions Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Billie Jo Favorite","areas":["Safety Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Autumn Perez","areas":["Hospitality"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Nicolas Davila","areas":["Media Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Junior Costa","areas":["Band 4th Service"],"campus":"brazilian","perMonth":3,"tier":"medium"},
  {"name":"Alexandre De Oliveira","areas":["Safety Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Rojer Tewari","areas":["Hospitality"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Yehoshua Arroyo","areas":["Ushers"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Lorie Thernelus","areas":["Media Team"],"campus":"english","perMonth":3,"tier":"medium"},
  {"name":"Cheryl Romanoski","areas":["Kids Point JR","K-3rd Grade","Ages 2 - 5","Check-In Team"],"campus":"english","perMonth":2,"tier":"high"},
  {"name":"Emmanuel Jenkins","areas":["Band","Youth Group Worship Team","Overflow Tent","Growth Group Agenda Writers"],"campus":"english","perMonth":2,"tier":"high"},
  {"name":"Antoinette Crowl Grey","areas":["Check-In Volunteers","Kids Point JR","Kids Point"],"campus":"english","perMonth":2,"tier":"high"},
  {"name":"Kiana Samuel","areas":["Check-In Volunteers","K-3rd Grade","Check-In Team"],"campus":"english","perMonth":2,"tier":"high"},
  {"name":"Lexi Jenkins","areas":["Kids Point JR","K-3rd Grade","Kids Point"],"campus":"english","perMonth":2,"tier":"high"},
  {"name":"Julia Costa","areas":["Kids 4th Service","Youth Group Worship Team","Tech 4th Service"],"campus":"both","perMonth":2,"tier":"high"},
  {"name":"Josiane Peixoto Vizintin","areas":["Diaconia - FPC Brasil","Kids 4th Service","Vocals 4th Service"],"campus":"brazilian","perMonth":2,"tier":"high"},
  {"name":"Hilary Veguilla","areas":["Kids Point JR","Hospitality","K-3rd Grade"],"campus":"english","perMonth":2,"tier":"high"},
  {"name":"Eliana Veguilla","areas":["Kids Point","K-3rd Grade","Ages 2 - 5"],"campus":"english","perMonth":2,"tier":"high"},
  {"name":"Michelle Pla","areas":["Vocals","Youth Group Worship Team"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Faith Knight","areas":["Check-In Volunteers","Check-In Team"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Pam Campbell","areas":["Check-In Volunteers","First Impressions Team"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Sabinah Rodriguez","areas":["Vocals","Overflow Tent"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Marisol Rodriguez - Rivera","areas":["Hospitality","YTH Services"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Angielique (Angie) Arroyo","areas":["Ushers","First Steps Nursery"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Clarissa Diaz","areas":["Vocals","Kids Point"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Treasure Montanez","areas":["Kids Point JR","Kids Point"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Chelsea Trask","areas":["Vocals","Overflow Tent"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Jefferson Thernelus","areas":["Band","Youth Group Worship Team"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Elizabeth Elias","areas":["Vocals 4th Service","Diaconia - FPC Brasil"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Manuel Luciani","areas":["Kids Point","Hospitality"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Nayme Fritz","areas":["First Impressions Team","Hospitality"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Kaitlynn Cassier","areas":["Kids Point JR","YTH Services"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Annmarie Soto","areas":["First Steps Nursery","Hospitality"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Juliana Davila","areas":["Band","Vocals"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Selma White","areas":["Diaconia - FPC Brasil","Vocals 4th Service"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Kyla Casillo","areas":["Kids 4th Service","Youth Group Worship Team"],"campus":"both","perMonth":2,"tier":"medium"},
  {"name":"Abiezer Morales","areas":["First Impressions Team","Kids Point"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Ricardo Giaretta","areas":["Band 4th Service","Kids 4th Service"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Mika Noel","areas":["First Steps Nursery","Check-In Team"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Nathan Freitas","areas":["Vocals 4th Service","Band 4th Service"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Bianca Peixoto Vizintin","areas":["Kids 4th Service","Tech 4th Service"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Juliana Teixeira","areas":["Diaconia - FPC Brasil","Kids 4th Service"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Carolina Santos","areas":["Diaconia - FPC Brasil","Apoio Pastoral"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Erik Rodriguez","areas":["Media Team","Band"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Juanita Pimentel","areas":["First Impressions Team","Ushers"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Ana Gadelna","areas":["Vocals","Overflow Tent"],"campus":"english","perMonth":2,"tier":"medium"},
  {"name":"Cairon Oliveira","areas":["Tech 4th Service","Band 4th Service"],"campus":"brazilian","perMonth":2,"tier":"medium"},
  {"name":"Maria Yudice","areas":["Kids Point JR","Kids Point","K-3rd Grade","Ages 2 - 5"],"campus":"english","perMonth":1,"tier":"high"},
  {"name":"Julissa Garcia","areas":["Kids Point","Tech","Kids Point JR"],"campus":"english","perMonth":1,"tier":"high"},
  {"name":"Ariah Rivera","areas":["Check-In Volunteers","Ages 2 - 5","Kids Point"],"campus":"english","perMonth":1,"tier":"high"},
  {"name":"Elegance Sanborn","areas":["Kids Point JR","First Impressions Team","First Steps Nursery"],"campus":"english","perMonth":1,"tier":"high"},
  {"name":"Brenda Almeida","areas":["Kids 4th Service","Tech 4th Service","Vocals 4th Service"],"campus":"brazilian","perMonth":1,"tier":"high"},
  {"name":"Aisha Sostre","areas":["Nursery - Saturday","K-3rd Grade"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Wyatt Horne","areas":["Parking Team","Youth Group Worship Team"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Carol Nasseh","areas":["Kids Point JR","Kids Point"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Amaia Montalvo-Bentz","areas":["Tech","Youth Group Worship Team"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Gibeth Santana","areas":["Check-In Volunteers","First Steps Nursery"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Dilylah Falcon","areas":["First Steps Nursery","YTH Services"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Jodie Foster","areas":["Reception Team","First Impressions Team"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Malyssa Pena Acosta","areas":["First Steps Nursery","K-3rd Grade"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Edijane Vieira","areas":["Kids 4th Service","Diaconia - FPC Brasil"],"campus":"brazilian","perMonth":1,"tier":"medium"},
  {"name":"Michelle Martinez","areas":["Check-In Volunteers","Kids Point"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Anais Hernandez","areas":["K-3rd Grade","Ages 2 - 5"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Alfredo Hernandez","areas":["K-3rd Grade","Ages 2 - 5"],"campus":"english","perMonth":1,"tier":"medium"},
  {"name":"Bianca Vizintin","areas":["Kids 4th Service","Tech 4th Service"],"campus":"brazilian","perMonth":1,"tier":"medium"},
  {"name":"Yolonda Earls","areas":["Kids Point","K-3rd Grade"],"campus":"english","perMonth":1,"tier":"medium"},
  ],
  drafts: [],
}
