// Focal Point Church - congregation of each flagged person and family, for the
// Brazilian lens (real, from scripts/gen-congregation.mjs).
// Signal: which Sunday service they attend (6pm = Brazilian), backed by group
// membership and, for families, their kids' service. congregationOf resolves a
// person's name OR a family surname OR the "The {Name} family" display form.
// Guests are absent (they sign in at Starting Point, not a service, so they have
// no congregation yet). People with no check-in signal are absent too and only
// show in the 'all' scope.
// LOCAL OVERRIDE (skip-worktree): real names live on disk only, never in git.
export type Congregation = "brazilian" | "english"
export const focalPointCongregation: Record<string, Congregation> = {
  "aaron score": "brazilian",
  "abby galindo": "english",
  "abiezer morales": "english",
  "adriana moreno": "english",
  "aisha sostre": "english",
  "alfredo hernandez": "english",
  "allie smallwood": "english",
  "ally": "english",
  "alondra moreno": "english",
  "amaia montalvo-bentz": "english",
  "amanda walters": "brazilian",
  "ana gadelha": "english",
  "anais hernandez": "english",
  "andre faleiros": "brazilian",
  "andrea albarran": "english",
  "andrew marrero": "english",
  "andrew wright": "english",
  "angielique (angie) arroyo": "english",
  "annmarie soto": "english",
  "anthony jr. velasquez": "english",
  "antoinette crowl grey": "english",
  "antonio garcia": "english",
  "ariah rivera": "english",
  "ashley elicier": "english",
  "autumn perez": "english",
  "aykel irizarry": "english",
  "beatriz price": "english",
  "billie jo favorite": "english",
  "black": "english",
  "bradshaw": "english",
  "bwansa": "english",
  "cadet": "english",
  "cairon oliveira": "brazilian",
  "calen donohue": "english",
  "camila aguirre": "english",
  "camilo rojas": "english",
  "carol nasseh": "english",
  "caroline da silva": "brazilian",
  "carvalho": "brazilian",
  "cassie wiggins": "english",
  "cassier": "english",
  "caucheline romain": "english",
  "cediel": "english",
  "challenger": "english",
  "chelsea trask": "english",
  "cheryl romanoski": "english",
  "chiratanagandla": "english",
  "clarissa diaz": "english",
  "cleusa trindade": "brazilian",
  "costa": "brazilian",
  "costs": "brazilian",
  "courtland skipper": "english",
  "cristian veguilla": "english",
  "crowl grey": "english",
  "cruz jr": "english",
  "daisy amore": "english",
  "damelio": "english",
  "dana bennett": "english",
  "daniel": "english",
  "daniel miranda": "english",
  "daniel rivera": "english",
  "darryl jefferson": "english",
  "dave mcnichols": "english",
  "david thomas": "english",
  "dawnita anderson": "english",
  "diego rodriguez": "brazilian",
  "dilylah falcon": "english",
  "dj veguilla": "brazilian",
  "donna sproat": "english",
  "dove": "english",
  "eddie del valle": "english",
  "edijane vieira": "brazilian",
  "elane alves": "brazilian",
  "elegance sanborn": "english",
  "eliana veguilla": "brazilian",
  "elizabeth elias": "brazilian",
  "emmanuel jenkins": "english",
  "eric campbell": "english",
  "erik abbass": "english",
  "erik rodriguez": "english",
  "escobar": "english",
  "faith knight": "english",
  "farmer": "english",
  "farmer jr": "english",
  "fernando barros": "brazilian",
  "ferrer": "english",
  "fouche": "english",
  "frederico vasconcelos": "brazilian",
  "gianna olivas": "english",
  "gibeth santana": "english",
  "glenn eppinger": "english",
  "gomes": "brazilian",
  "gonzalez": "brazilian",
  "guzman": "english",
  "hammonds": "english",
  "hart": "brazilian",
  "hilary veguilla": "english",
  "isabel lamberty": "english",
  "isabella alvira": "english",
  "jason del moral": "english",
  "javenson romain": "english",
  "jefferson thernelus": "english",
  "jen villanueva": "english",
  "jenkins": "english",
  "jennifer kneefe": "english",
  "jeshua rodriguez": "english",
  "jessica geil": "english",
  "joan de pass": "english",
  "johanny moya": "english",
  "john fritz": "english",
  "joshua matos": "english",
  "jr rivera": "english",
  "juan rojas": "english",
  "juanita pimentel": "english",
  "julia costa": "english",
  "juliana davila": "english",
  "juliana teixeira": "brazilian",
  "julio rivera": "english",
  "julissa romain": "english",
  "kaitlynn cassier": "english",
  "keenan bowers": "english",
  "keith wright": "english",
  "keren silva": "brazilian",
  "kiana samuel": "english",
  "kristof salopek": "english",
  "kyla casillo": "brazilian",
  "kyria thernelus": "english",
  "lee": "english",
  "leslie jameel": "english",
  "lexi jenkins": "english",
  "liam secord": "english",
  "linda skipper": "english",
  "lorie thernelus": "english",
  "lydia salopek": "english",
  "maciel": "brazilian",
  "manuel luciani": "english",
  "marcela bunch": "brazilian",
  "margaret lahee": "english",
  "maria rojas": "english",
  "maria yudice": "english",
  "marisol rodriguez - rivera": "english",
  "mark manigold": "english",
  "matos": "english",
  "mauvais": "english",
  "mcgriff": "english",
  "merino": "english",
  "merino iii": "english",
  "michael alvarez": "english",
  "michael neubauer": "english",
  "michelle pla": "english",
  "miguel oliveira": "brazilian",
  "mika noel": "english",
  "milliotti": "english",
  "mirabela dragoiu": "english",
  "mitrano": "english",
  "mitrano iii": "english",
  "morissaint": "english",
  "murillo alves": "brazilian",
  "nathalie lubin": "english",
  "nathan freitas": "brazilian",
  "nicolas davila": "english",
  "nikolas correa": "english",
  "otero": "english",
  "pam campbell": "english",
  "peter bankole": "english",
  "puga": "brazilian",
  "ramonita cotte serrano": "english",
  "raquel araujo": "brazilian",
  "rebeca alves": "brazilian",
  "ricardo giaretta": "brazilian",
  "robert matos": "english",
  "roberto j serrano": "english",
  "rodriguez": "english",
  "rojer tewari": "english",
  "sabinah rodriguez": "brazilian",
  "samantha geil": "english",
  "sandoval": "english",
  "sandra buitrago": "english",
  "santana": "brazilian",
  "sean anger": "english",
  "sebastian aleman": "english",
  "short": "english",
  "silva": "brazilian",
  "speck": "english",
  "tahlia louis": "english",
  "teixeira": "brazilian",
  "thayana xavier silva": "english",
  "tracy lipoa thomas": "english",
  "treasure montanez": "english",
  "trenesia jefferson": "english",
  "vaiaoga": "english",
  "vargas": "english",
  "vieira": "brazilian",
  "walker": "english",
  "wendy toro": "english",
  "william walters": "brazilian",
  "winston knight": "english",
  "wyatt horne": "english",
  "xavier silva": "english",
  "yehoshua arroyo": "english",
  "yolonda earls": "english",
}
const norm = (name: string) => name.toLowerCase().replace(/\s+/g, " ").trim()
export function congregationOf(name: string): Congregation | null {
  const k = norm(name)
  if (focalPointCongregation[k]) return focalPointCongregation[k]
  // family display form: "The {Name} family" -> "{name}"
  const fam = k.replace(/^the\s+/, "").replace(/\s+family$/, "").trim()
  return focalPointCongregation[fam] ?? null
}
export const focalPointCongregationStats = {
  brazilianGroups: 13,
  englishGroups: 47,
  brazilianPeople: 277,
  englishPeople: 655,
}
