// Focal Point Church - guest pipeline (real, from the two Starting Point
// workflows via scripts/gen-guest-pipeline.mjs). Each guest is tagged by
// congregation (English weekend service vs Brazilian service) so Front Desk &
// Guests scopes. Stage from the follow-up step. LOCAL OVERRIDE (skip-worktree):
// real congregant names live on disk only, never in git.
export type GuestStage = 'new' | 'welcomed' | 'connecting' | 'belongs' | 'cooled'
export type GuestCampus = 'english' | 'brazilian'
export const GUEST_STAGES: { key: GuestStage; label: string; positive?: boolean; leak?: boolean }[] = [
  { key: 'new', label: 'New guest' },
  { key: 'welcomed', label: 'Welcomed' },
  { key: 'connecting', label: 'Connecting' },
  { key: 'belongs', label: 'Belongs', positive: true },
  { key: 'cooled', label: 'Cooled', leak: true },
]
export interface GuestCase {
  id: string
  name: string
  campus: GuestCampus
  stage: GuestStage
  detail: string
  owner: string
  age: string
  note?: string
  draft?: string
  outcome?: string
}
export interface GuestKpis { recentGuests: number; firstTimers4w: number; stillVisitors: number; completedPct: number }
export const guestPipeline: { cases: GuestCase[]; kpis: Record<'all' | GuestCampus, GuestKpis> } = {
  cases: [
    {"id":"gp-1","name":"Bennalee Vasquez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Bennalee, we were so glad you joined us at Focal Point on Sunday. We know finding a church home looks different for every person, and we would be honored to walk alongside you this season. If we can help in any way, just reply here. Blessings, Pastor Mark"},
    {"id":"gp-2","name":"Yuisa Cruz","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Yuisa, we were so glad you joined us at Focal Point on Sunday. We know finding a church home looks different for every person, and we would be honored to walk alongside you this season. If we can help in any way, just reply here. Blessings, Pastor Mark"},
    {"id":"gp-3","name":"Adam Hope","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Adam, we were so glad you joined us at Focal Point on Sunday. We know finding a church home looks different for every person, and we would be honored to walk alongside you this season. If we can help in any way, just reply here. Blessings, Pastor Mark"},
    {"id":"gp-4","name":"Lidia Soares","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Lidia, we were so glad you joined us at Focal Point on Sunday. We know finding a church home looks different for every person, and we would be honored to walk alongside you this season. If we can help in any way, just reply here. Blessings, Pastor Mark"},
    {"id":"gp-5","name":"Steven Tsukamoto","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Steven, we were so glad you joined us at Focal Point on Sunday. We know finding a church home looks different for every person, and we would be honored to walk alongside you this season. If we can help in any way, just reply here. Blessings, Pastor Mark"},
    {"id":"gp-6","name":"Fodly Hyppolite","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Fodly, we were so glad you joined us at Focal Point on Sunday. We know finding a church home looks different for every person, and we would be honored to walk alongside you this season. If we can help in any way, just reply here. Blessings, Pastor Mark"},
    {"id":"gp-7","name":"Hermite Salomon","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Hermite, we were so glad you joined us at Focal Point on Sunday. We know finding a church home looks different for every person, and we would be honored to walk alongside you this season. If we can help in any way, just reply here. Blessings, Pastor Mark"},
    {"id":"gp-8","name":"Rudelis Martinez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"2w ago"},
    {"id":"gp-9","name":"Ranffi Ramirez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"2w ago"},
    {"id":"gp-10","name":"Grace Utama","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"2w ago"},
    {"id":"gp-11","name":"Hope Shegay","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"2w ago"},
    {"id":"gp-12","name":"Jacquez Carter","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"2w ago"},
    {"id":"gp-13","name":"Rachel Delgado","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"2w ago"},
    {"id":"gp-14","name":"Miguel Baruque","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"2w ago"},
    {"id":"gp-15","name":"Thaliciany Machado","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"3w ago"},
    {"id":"gp-16","name":"Emma Tate","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"3w ago"},
    {"id":"gp-17","name":"Jin Xiang","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"3w ago"},
    {"id":"gp-18","name":"Penny Battjes","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-19","name":"Paul Battjes","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-20","name":"Julian Santos","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-21","name":"Angelina Freundt","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-22","name":"Jade Henderson","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-23","name":"Daniel Rojas","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-24","name":"Donna Martin","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-25","name":"Arturo Otero","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-26","name":"Handeson Machado","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-27","name":"Evelyn Correa","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-28","name":"Nan Miller","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-29","name":"Nazeema Khan","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-30","name":"Ana Smith","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-31","name":"Anthea Alley","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-32","name":"Noah Alley","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-33","name":"Belinda Alley","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-34","name":"Taeja Cannella","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-35","name":"Robbin Janaque","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-36","name":"Zari Campbell","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-37","name":"Sara Sandoval","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-38","name":"Amy Noble","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-39","name":"Roxana Ramirez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"6w ago"},
    {"id":"gp-40","name":"Kristine Valenciano","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-41","name":"Jason Soderlund","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-42","name":"Joe Redmond","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-43","name":"Todd Adolphe","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-44","name":"Xiomaris Legarreta","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-45","name":"Qyanna Javier","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-46","name":"Flavio Konno","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-47","name":"Mary Stewart","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-48","name":"Jesse Moorhouse","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-49","name":"Adrian Fuentes","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-50","name":"Luma Mueller","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-51","name":"Jay Thibodeau","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-52","name":"Katia Marlon","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-53","name":"Noah Gouge","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-54","name":"Leah Fry","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-55","name":"Lorenzo Williams","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-56","name":"Sheyla T","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-57","name":"Payton Schermerhorn","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-58","name":"Mariliana Roman","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-59","name":"Christina Hernandez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-60","name":"Quincy Epps","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-61","name":"Wanda Redmond","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-62","name":"Catalina Cortavitarte","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-63","name":"Freddy Mercado","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-64","name":"Junior Carauba","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-65","name":"Roxanne Contrino","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-66","name":"Evelyn Velez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-67","name":"Sofia Medina","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-68","name":"Jessica Moore","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-69","name":"Amanda Grahn","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-70","name":"Toni Israel","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-71","name":"Elizabeth Melendez","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-72","name":"Jake Kunzler","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-73","name":"Ruth Rosario Martinez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-74","name":"Miguel Rosa","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-75","name":"Sandra Howard","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-76","name":"Plainse. Jettoo","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-77","name":"Lyssette Scharffenorth","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-78","name":"Erika and Enrique Goyzueta","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-79","name":"Audrey Wilcox","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-80","name":"Jeannette Mohess","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-81","name":"Mulanmarie Phifer","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-82","name":"Jon Ramsis","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-83","name":"Evelyn Phifer","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-84","name":"Zaidy Velez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-85","name":"Samuel Gonzalez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-86","name":"Betzaida Lopez","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-87","name":"Cristiane Anderson","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-88","name":"Talia Gallagher","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-89","name":"Danielle Teirelbaum","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"17w ago"},
    {"id":"gp-90","name":"Genesis Mejia","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"18w ago"},
    {"id":"gp-91","name":"Sara Valencia","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"18w ago"},
    {"id":"gp-92","name":"Tiana Chelle","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"18w ago"},
    {"id":"gp-93","name":"Amy Anderson","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-94","name":"Amy Vandessppooll","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-95","name":"Laleshka Gelpi","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-96","name":"Joshua Morales","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-97","name":"Melissa Tejada","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-98","name":"Heath Davis","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-99","name":"Leahn Platero","campus":"english","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-100","name":"Luis Ferreyra","campus":"english","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"20w ago"},
    {"id":"gp-101","name":"Maryelsy Zerpa","campus":"english","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"20w ago"},
    {"id":"gp-102","name":"Acacio Lima","campus":"brazilian","stage":"new","detail":"first visit · signed in at Starting Point","owner":"Pastor Mark","age":"this week","note":"Grace drafted a welcome, awaiting your approval","draft":"Acacio, foi uma alegria ter você conosco na Focal Point no domingo. Sabemos que encontrar uma igreja é diferente para cada pessoa, e seria uma honra caminhar ao seu lado nesta temporada. Se pudermos ajudar de alguma forma, é só responder aqui. Bênçãos, Pastor"},
    {"id":"gp-103","name":"Fabiana Lima","campus":"brazilian","stage":"new","detail":"first visit · signed in at Starting Point","owner":"Pastor Mark","age":"2w ago"},
    {"id":"gp-104","name":"Carlos Alberto de Souza","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-105","name":"Fabiana Carvalho de Lima","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-106","name":"Celia Nascimento","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"4w ago"},
    {"id":"gp-107","name":"Lucy Domingues","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-108","name":"Moises Marques","campus":"brazilian","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-109","name":"Leonara Paiva","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-110","name":"Mariana Faria","campus":"brazilian","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"5w ago"},
    {"id":"gp-111","name":"Alessandro Teixeira Vasconcelos","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-112","name":"Talissa de Jesus","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-113","name":"Ricardo Pinheiro","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-114","name":"Thamires Jardim","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-115","name":"Danilo Pereira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-116","name":"Gawens Pierre","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"7w ago"},
    {"id":"gp-117","name":"Cynthia Giovanini","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-118","name":"Gonçalo Freire","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-119","name":"Marisa Ferreira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-120","name":"Elisangela Alves Da Silva","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-121","name":"Carlos Vega","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"8w ago"},
    {"id":"gp-122","name":"Joel Vargas","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-123","name":"Giovanna Vargas","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-124","name":"Giovana Braido","campus":"brazilian","stage":"cooled","detail":"signed in weeks ago · no next step since","owner":"Connections team","age":"9w ago"},
    {"id":"gp-125","name":"Luis Henrique Mariani","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-126","name":"Ester Harckbart","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-127","name":"Jean Nunes","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-128","name":"Bruno Barbosa","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"9w ago"},
    {"id":"gp-129","name":"Claudia Pereira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-130","name":"Enoys Leuco","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-131","name":"Denilson Visitante","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-132","name":"Marcelo Pereira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-133","name":"John Conor","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-134","name":"Ester Maranho","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-135","name":"Alexandra Santos","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-136","name":"Wagner Oliveira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-137","name":"Copper Phillips","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-138","name":"Katherine Andercia","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"10w ago"},
    {"id":"gp-139","name":"Adriana Campos","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-140","name":"Amanda Santos","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-141","name":"Joao Neto","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"11w ago"},
    {"id":"gp-142","name":"Deborah Rangel","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-143","name":"Luan Augusto Carvalho","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-144","name":"Miguel Rangel","campus":"brazilian","stage":"cooled","detail":"signed in weeks ago · no next step since","owner":"Connections team","age":"12w ago"},
    {"id":"gp-145","name":"Miguel Rangel","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-146","name":"Paula Rodrigues","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-147","name":"Kaylani Rangel","campus":"brazilian","stage":"cooled","detail":"signed in weeks ago · no next step since","owner":"Connections team","age":"12w ago"},
    {"id":"gp-148","name":"Raphaela Andrade de Moura","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-149","name":"Bruna Santos","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-150","name":"Kayo Santos","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-151","name":"Gessy Furtado","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-152","name":"Deborah Rangel","campus":"brazilian","stage":"cooled","detail":"signed in weeks ago · no next step since","owner":"Connections team","age":"12w ago"},
    {"id":"gp-153","name":"Roosevett Salviano","campus":"brazilian","stage":"belongs","detail":"finished the welcome sequence","owner":"Grace, auto","age":"12w ago"},
    {"id":"gp-154","name":"Joel Vargas","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-155","name":"Renata Borges","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-156","name":"Luis Fernando Nunes","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-157","name":"Cleo Silva","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-158","name":"Mariana Rodrigues de Souza","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-159","name":"Lorena Rodrigues","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-160","name":"Joana Gomes","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"13w ago"},
    {"id":"gp-161","name":"Juliana Martins","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-162","name":"Alexandre Magno","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-163","name":"Victor Guilherme da Silva","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-164","name":"Fernando Danilo da Silva","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-165","name":"Vitor Rech Takla","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-166","name":"Giovani Oliveira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-167","name":"Jeferson Yue","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-168","name":"Karen Bermudes","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-169","name":"Sabrina Lugg","campus":"brazilian","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-170","name":"Helton Oliveira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-171","name":"Roseane Rodrigues","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-172","name":"Aline Joakim","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-173","name":"Katia Sabina","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-174","name":"Mel Bermudes","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-175","name":"Ana Paula Rech Takla","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-176","name":"Magda Cruz","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-177","name":"Carla Bermudes","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-178","name":"Sandra Lugg","campus":"brazilian","stage":"connecting","detail":"week-3 follow-up · progressing","owner":"Grace, auto","age":"14w ago"},
    {"id":"gp-179","name":"Gessiane Domingues Furtado","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-180","name":"Eloa Silva","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-181","name":"Carlos Andre Vale","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-182","name":"Fabiana Pacheco do Vale","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"15w ago"},
    {"id":"gp-183","name":"Andressa Oliveira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-184","name":"Gabriella Eller","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-185","name":"Cristina Teixeira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-186","name":"Lorena Teixeira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-187","name":"Marianne Geraldes","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-188","name":"Luisa Cristina do Val","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-189","name":"Leonardo Teixeira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-190","name":"Paulo Oliveira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-191","name":"Davi de Oliveira","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"16w ago"},
    {"id":"gp-192","name":"Larissa Bueno","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-193","name":"Melissa Camacho","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-194","name":"Marcos Alberto Camacho","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-195","name":"Ademir Leal","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-196","name":"Dione Leal","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-197","name":"Gustavo Trevisan","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-198","name":"Andressa Galassi","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-199","name":"Adriana Almeida","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-200","name":"Hemerson Viana","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-201","name":"Katiane Teodoro","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-202","name":"Daniel Conti","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-203","name":"Franciele Conti","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
    {"id":"gp-204","name":"Larissa Bueno","campus":"brazilian","stage":"welcomed","detail":"welcome sent · in the week-2 follow-up","owner":"Grace, auto","age":"19w ago"},
  ],
  kpis: {
    "english": {
      "recentGuests": 101,
      "firstTimers4w": 23,
      "stillVisitors": 89,
      "completedPct": 12
    },
    "brazilian": {
      "recentGuests": 103,
      "firstTimers4w": 2,
      "stillVisitors": 95,
      "completedPct": 8
    },
    "all": {
      "recentGuests": 204,
      "firstTimers4w": 25,
      "stillVisitors": 184,
      "completedPct": 10
    }
  },
}
export function guestKpis(scope: 'all' | GuestCampus): GuestKpis {
  return guestPipeline.kpis[scope]
}
